/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState, useEffect } from "react";
import Logo from "../components/elements/branding/Logo";
import LandingContent from "../components/content/LandingContent";
import Dialogue from "../components/elements/dialoguebox/Dialogue";
import Footer from "../components/elements/branding/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
    
    const [ isPromptViewOpen, setIsPromptViewOpen ] = useState(false);
    console.log('loading');
    
    return (
        <div className={styles.container}>
            <Head>
                <title>OpenResponse</title>
                <meta
                    name="OpenResponse is an AI prompt-completion client"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/ico.svg" />
            </Head>

            <main className={styles.main}>
                <Logo />
                {/* {!isPromptViewOpen && <LandingContent isPromptViewOpen={isPromptViewOpen} setIsPromptViewOpen={setIsPromptViewOpen}/>}
                {isPromptViewOpen && <Dialogue />} */}
                <Dialogue />
            </main>
            <Footer />
        </div>
    );
}
